# Generated by Django 4.1 on 2022-11-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="source",
            field=models.CharField(
                choices=[
                    ("SALARY", "SALARY"),
                    ("BUSINESS", "BUSINESS"),
                    ("OTHERS", "OTHERS"),
                ],
                max_length=255,
            ),
        ),
    ]
