# Generated by Django 4.0.5 on 2022-11-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_expense_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Описание'),
        ),
    ]
