# Generated by Django 4.0.5 on 2022-11-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_alter_expense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='time',
        ),
    ]
