# Generated by Django 4.0.5 on 2022-11-06 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_remove_expense_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
